backend:
  name: github
  repo: mtoni2/mundotecno
  branch: main
  auth_type: implicit
  app_id: Ov23liHFvMkWIUsua1EQ

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del Producto", name: "title", widget: "string" }
      - { label: "Precio", name: "precio", widget: "number", value_type: "float" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Audio", "Accesorios", "Cargadores", "Varios"] }
      - { label: "Descripción", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "En Stock", name: "stock", widget: "boolean", default: true }
